### ISSUE TITLE
Disable GitHub message

### ISSUE THREAD

**Issue by LeoIannacone** [imsky/pull-review#76]
Hi,

I think the github message is superfluous in some cases:
 * people will receive the Review assignment email
 * (if chat) they will be notified in the chat channel

Is there a simple way to disable it ?

**Comment by imsky** [comment]
@LeoIannacone this is intentional, so that there's a record of assignment on the PR and an immediate notification in the chat environment. i can see how it might not fit everyone's style though. i appreciate the changes you suggested in #77, but i think this should be a configurable option rather than a complete behavior change.

**Comment by LeoIannacone** [comment]
@imsky thanks for suggestion, I worked on it and added new options (env variables)
